version: '3.8'

services:
  prodigy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
      - PRODIGY_HOME=/app/config
    volumes:
      - ./config:/app/config
    restart: unless-stopped